/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdint.h>

#define ADC_BASE_ADDR		0x40012000UL

#define ADC_CR1_REG_OFFSET	0x04UL

#define ADC_CR1_REG_ADDR	(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

int main(void)
{
    uint32_t *pAdcCr1Reg = (uint32_t*)ADC_CR1_REG_ADDR;

    *pAdcCr1Reg |= (1 << 8);	// Bit 8 SCAN: Scan mode

	for(;;);
}
